### ISSUE TITLE
BOM Table Missing

### ISSUE THREAD

**Issue by WMixter20** [cgxeiji/cgxkb#1]
Hi, I recently found this keyboard design and thought about making a version for me to use however when looking through the build guide I noticed that the BOM table was missing.

I copied what is there currently there below:
>Bill of Materials (BOM)
>First, let's make sure we have all the components necessary to build the keyboard.
>[insert table]

**Comment by cgxeiji** [comment]
@WMixter20 Thank you so much for showing interest in this project!

This is a personal hobby of mine, so I apologize if development is slow. I was planning on releasing version 1.0.0 of the keyboard, but ran out of funds to finish development. I might have some time during the upcoming holidays to update the BOM so you can order the components from your local supplier. I hope you have the patience to wait for a little while.

Thank you!

**Comment by cgxeiji** [comment]
Closed with [e6ada61](https://github.com/cgxeiji/cgxkb/commit/e6ada614ae1d6486f74c7c6fa3a175d93addb6b3).
